glorys_dir: /scratch/cimes/bz5265/MOM_ICs_OBCs/scripts/temp/20240922
output_dir: /scratch/cimes/bz5265/MOM_ICs_OBCs/scripts/temp/
hgrid: /scratch/cimes/bz5265/MOM_ICs_OBCs/grid/C3200/ocean_hgrid.nc 
ncrcat_years: true  # Set to false if you want to skip ncrcat_years
ncrcat_names:
  - 'thetao'
  - 'so'
  - 'zos'
  - 'uv'
variables:
  - 'thetao'
  - 'so'
  - 'zos'
  - 'uv'
segments:
  - id: 1
    border: 'south'
  - id: 2
    border: 'north'
  - id: 3
    border: 'east'
